#! /bin/bash
SSH_KEY=$HOME/.ssh/sshkey # location of ssh key on your local computer
SERVER_URL=46.101.168.182 # public ip address of the server
PATH_TO_SCRIPT=$HOME/demo/localScript # path to local script on your local computer

# copy over local script to server
scp -i $SSH_KEY $PATH_TO_SCRIPT root@$SERVER_URL:~

# ssh into server and install node
ssh -i $SSH_KEY root@$SERVER_URL "./localScript"
